theme: jekyll-theme-cayman
title: "Open positions in computer vision"
github:
  is_project_page: false
[//]: #description: "Call for doctoral students"
[//]: #theme: jekyll-theme-cayman
[//]: #theme: jekyll-theme-slate
[//]: #theme: jekyll-theme-hacker
[//]: #title: "Open positions in computer vision"
